/**
 * Color scheme utility for the wedding site
 * Returns Tailwind CSS classes based on the selected color scheme
 * 
 * Available schemes: 'pink' | 'rose' | 'purple' | 'blue' | 'teal' | 'green' | 'sage' | 'red'
 */

export type ColorSchemeName = 'pink' | 'rose' | 'purple' | 'blue' | 'teal' | 'green' | 'sage' | 'red'

/**
 * Get Tailwind classes for a color scheme
 * This function returns complete class strings that Tailwind can detect at build time
 */
export function getColorClasses(scheme: ColorSchemeName = 'pink') {
  const classes = {
    pink: {
      // Background colors
      bgLight: 'bg-pink-50',
      gradientFrom: 'from-pink-50',
      gradientTo: 'to-pink-50',
      bgLightHover: 'hover:bg-pink-100',
      bgMedium: 'bg-pink-400',
      bgDark: 'bg-pink-600',
      bgDarkHover: 'hover:bg-pink-700',
      
      // Text colors
      text: 'text-pink-600',
      textDark: 'text-pink-600',
      textHover: 'hover:text-pink-600',
      
      // Border colors
      borderLight: 'border-pink-100',
      borderMedium: 'border-pink-400',
      borderDark: 'border-pink-600',
      borderHover: 'hover:border-pink-400',
      
      // Ring colors (for focus states)
      ring: 'focus:ring-pink-600',
      focusBorder: 'focus:border-pink-600',
      accent: 'accent-pink-600',
      
      // Icon colors
      icon: 'text-pink-600',
      textMedium: 'text-pink-500',
      // Flower decoration colors
      flowerOuter: 'text-pink-400',
      flowerInner: 'fill-pink-300',
      flowerCenter: 'fill-pink-500',
      leaf: 'text-green-400',
      branch: 'text-green-500',
    },
    rose: {
      bgLight: 'bg-rose-50',
      gradientFrom: 'from-rose-50',
      gradientTo: 'to-rose-50',
      bgLightHover: 'hover:bg-rose-100',
      bgMedium: 'bg-rose-400',
      bgDark: 'bg-rose-600',
      bgDarkHover: 'hover:bg-rose-700',
      text: 'text-rose-600',
      textDark: 'text-rose-600',
      textHover: 'hover:text-rose-600',
      borderLight: 'border-rose-100',
      borderMedium: 'border-rose-400',
      borderDark: 'border-rose-600',
      borderHover: 'hover:border-rose-400',
      ring: 'focus:ring-rose-600',
      focusBorder: 'focus:border-rose-600',
      accent: 'accent-rose-600',
      icon: 'text-rose-600',
      textMedium: 'text-rose-500',
      flowerOuter: 'text-rose-400',
      flowerInner: 'fill-rose-300',
      flowerCenter: 'fill-rose-500',
      leaf: 'text-green-400',
      branch: 'text-green-500',
    },
    purple: {
      bgLight: 'bg-purple-50',
      gradientFrom: 'from-purple-50',
      gradientTo: 'to-purple-50',
      bgLightHover: 'hover:bg-purple-100',
      bgMedium: 'bg-purple-400',
      bgDark: 'bg-purple-600',
      bgDarkHover: 'hover:bg-purple-700',
      text: 'text-purple-600',
      textDark: 'text-purple-600',
      textHover: 'hover:text-purple-600',
      borderLight: 'border-purple-100',
      borderMedium: 'border-purple-400',
      borderDark: 'border-purple-600',
      borderHover: 'hover:border-purple-400',
      ring: 'focus:ring-purple-600',
      focusBorder: 'focus:border-purple-600',
      accent: 'accent-purple-600',
      icon: 'text-purple-600',
      textMedium: 'text-purple-500',
      flowerOuter: 'text-purple-400',
      flowerInner: 'fill-purple-300',
      flowerCenter: 'fill-purple-500',
      leaf: 'text-green-400',
      branch: 'text-green-500',
    },
    blue: {
      bgLight: 'bg-blue-50',
      gradientFrom: 'from-blue-50',
      gradientTo: 'to-blue-50',
      bgLightHover: 'hover:bg-blue-100',
      bgMedium: 'bg-blue-400',
      bgDark: 'bg-blue-600',
      bgDarkHover: 'hover:bg-blue-700',
      text: 'text-blue-600',
      textDark: 'text-blue-600',
      textHover: 'hover:text-blue-600',
      borderLight: 'border-blue-100',
      borderMedium: 'border-blue-400',
      borderDark: 'border-blue-600',
      borderHover: 'hover:border-blue-400',
      ring: 'focus:ring-blue-600',
      focusBorder: 'focus:border-blue-600',
      accent: 'accent-blue-600',
      icon: 'text-blue-600',
      textMedium: 'text-blue-500',
      flowerOuter: 'text-blue-400',
      flowerInner: 'fill-blue-300',
      flowerCenter: 'fill-blue-500',
      leaf: 'text-green-400',
      branch: 'text-green-500',
    },
    teal: {
      bgLight: 'bg-teal-50',
      gradientFrom: 'from-teal-50',
      gradientTo: 'to-teal-50',
      bgLightHover: 'hover:bg-teal-100',
      bgMedium: 'bg-teal-400',
      bgDark: 'bg-teal-600',
      bgDarkHover: 'hover:bg-teal-700',
      text: 'text-teal-600',
      textDark: 'text-teal-600',
      textHover: 'hover:text-teal-600',
      borderLight: 'border-teal-100',
      borderMedium: 'border-teal-400',
      borderDark: 'border-teal-600',
      borderHover: 'hover:border-teal-400',
      ring: 'focus:ring-teal-600',
      focusBorder: 'focus:border-teal-600',
      accent: 'accent-teal-600',
      icon: 'text-teal-600',
      textMedium: 'text-teal-500',
      flowerOuter: 'text-teal-400',
      flowerInner: 'fill-teal-300',
      flowerCenter: 'fill-teal-500',
      leaf: 'text-teal-400',
      branch: 'text-teal-500',
    },
    green: {
      bgLight: 'bg-green-100',
      gradientFrom: 'from-green-100',
      gradientTo: 'to-green-100',
      bgLightHover: 'hover:bg-green-200',
      bgMedium: 'bg-green-700',
      bgDark: 'bg-green-800',
      bgDarkHover: 'hover:bg-green-900',
      text: 'text-green-800',
      textDark: 'text-green-800',
      textHover: 'hover:text-green-800',
      borderLight: 'border-green-200',
      borderMedium: 'border-green-600',
      borderDark: 'border-green-800',
      borderHover: 'hover:border-green-700',
      ring: 'focus:ring-green-800',
      focusBorder: 'focus:border-green-800',
      accent: 'accent-green-800',
      icon: 'text-green-800',
      textMedium: 'text-green-700',
      flowerOuter: 'text-green-600',
      flowerInner: 'fill-green-500',
      flowerCenter: 'fill-green-700',
      leaf: 'text-green-500',
      branch: 'text-green-600',
    },
    sage: {
      // Sage - muted, dusty gray-green (custom palette)
      bgLight: 'bg-sage-100',
      gradientFrom: 'from-sage-100',
      gradientTo: 'to-sage-100',
      bgLightHover: 'hover:bg-sage-200',
      bgMedium: 'bg-sage-600',
      bgDark: 'bg-sage-700',
      bgDarkHover: 'hover:bg-sage-800',
      text: 'text-sage-700',
      textDark: 'text-sage-800',
      textHover: 'hover:text-sage-800',
      borderLight: 'border-sage-200',
      borderMedium: 'border-sage-500',
      borderDark: 'border-sage-700',
      borderHover: 'hover:border-sage-600',
      ring: 'focus:ring-sage-700',
      focusBorder: 'focus:border-sage-700',
      accent: 'accent-sage-700',
      icon: 'text-sage-700',
      textMedium: 'text-sage-600',
      flowerOuter: 'text-sage-500',
      flowerInner: 'fill-sage-400',
      flowerCenter: 'fill-sage-600',
      leaf: 'text-sage-500',
      branch: 'text-sage-600',
    },
    red: {
      bgLight: 'bg-red-50',
      gradientFrom: 'from-red-50',
      gradientTo: 'to-red-50',
      bgLightHover: 'hover:bg-red-100',
      bgMedium: 'bg-red-500',
      bgDark: 'bg-red-600',
      bgDarkHover: 'hover:bg-red-700',
      text: 'text-red-600',
      textDark: 'text-red-600',
      textHover: 'hover:text-red-600',
      borderLight: 'border-red-100',
      borderMedium: 'border-red-400',
      borderDark: 'border-red-600',
      borderHover: 'hover:border-red-400',
      ring: 'focus:ring-red-600',
      focusBorder: 'focus:border-red-600',
      accent: 'accent-red-600',
      icon: 'text-red-600',
      textMedium: 'text-red-500',
      flowerOuter: 'text-red-400',
      flowerInner: 'fill-red-300',
      flowerCenter: 'fill-red-500',
      leaf: 'text-green-400',
      branch: 'text-green-500',
    },
  }
  
  return classes[scheme]
}
